Traceback (most recent call last):
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/rblack/_dev/indoor-research/live-2022/.direnv/python-3.10.8/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fit_cl = fit_curve(x,raw_cl,smooth=True)
show_curve(x, smooth_cl,"Lift Coefficient","alpha","Cl")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/ws/5h_x4h713cg8w0jmrm5_tfzc0000gn/T/ipykernel_46134/3822775347.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mfit_cl[0m [0;34m=[0m [0mfit_curve[0m[0;34m([0m[0mx[0m[0;34m,[0m[0mraw_cl[0m[0;34m,[0m[0msmooth[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mshow_curve[0m[0;34m([0m[0mx[0m[0;34m,[0m [0msmooth_cl[0m[0;34m,[0m[0;34m"Lift Coefficient"[0m[0;34m,[0m[0;34m"alpha"[0m[0;34m,[0m[0;34m"Cl"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'show_curve' is not defined
NameError: name 'show_curve' is not defined

