Traceback (most recent call last):
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cl, cd, cm, cp = am.loadData('re3k')
print(cl(5), cd(5), cm(5))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/ws/5h_x4h713cg8w0jmrm5_tfzc0000gn/T/ipykernel_33890/1291258735.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mcl[0m[0;34m,[0m [0mcd[0m[0;34m,[0m [0mcm[0m[0;34m,[0m [0mcp[0m [0;34m=[0m [0mam[0m[0;34m.[0m[0mloadData[0m[0;34m([0m[0;34m're3k'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprint[0m[0;34m([0m[0mcl[0m[0;34m([0m[0;36m5[0m[0;34m)[0m[0;34m,[0m [0mcd[0m[0;34m([0m[0;36m5[0m[0;34m)[0m[0;34m,[0m [0mcm[0m[0;34m([0m[0;36m5[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/_dev/live-2022/mmtime/AirfoilMgr.py[0m in [0;36mloadData[0;34m(self, re)[0m
[1;32m     44[0m         [0mname[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mselected[0m[0;34m[0m[0;34m[0m[0m
[1;32m     45[0m         [0mprint[0m[0;34m([0m[0;34m"Loading"[0m[0;34m,[0m[0mself[0m[0;34m.[0m[0mselected[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 46[0;31m         [0mcpath[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mdatadir[0m[0;34m,[0m[0mname[0m[0;34m,[0m[0mre[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     47[0m         [0mcfiles[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mlistdir[0m[0;34m([0m[0mcpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     48[0m         [0;32mfor[0m [0mc[0m [0;32min[0m [0mcfiles[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py[0m in [0;36mjoin[0;34m(a, *p)[0m
[1;32m     88[0m                 [0mpath[0m [0;34m+=[0m [0msep[0m [0;34m+[0m [0mb[0m[0;34m[0m[0;34m[0m[0m
[1;32m     89[0m     [0;32mexcept[0m [0;34m([0m[0mTypeError[0m[0;34m,[0m [0mAttributeError[0m[0;34m,[0m [0mBytesWarning[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 90[0;31m         [0mgenericpath[0m[0;34m.[0m[0m_check_arg_types[0m[0;34m([0m[0;34m'join'[0m[0;34m,[0m [0ma[0m[0;34m,[0m [0;34m*[0m[0mp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     91[0m         [0;32mraise[0m[0;34m[0m[0;34m[0m[0m
[1;32m     92[0m     [0;32mreturn[0m [0mpath[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py[0m in [0;36m_check_arg_types[0;34m(funcname, *args)[0m
[1;32m    150[0m             [0mhasbytes[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    151[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 152[0;31m             raise TypeError(f'{funcname}() argument must be str, bytes, or '
[0m[1;32m    153[0m                             f'os.PathLike object, not {s.__class__.__name__!r}') from None
[1;32m    154[0m     [0;32mif[0m [0mhasstr[0m [0;32mand[0m [0mhasbytes[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

